services:
  approov-server:
    build: .
    container_name: approov-server
    working_dir: /home/python/workspace/server
    command: ["python", "-u", "hello_server_protected.py", "${HTTP_PORT:-8002}"]

    env_file:
      - ./server/config/.env
    environment:
      - DEV_DIR=/home/python/workspace/server/config
      - PYTHONUNBUFFERED=1

    volumes:
      - ./server:/home/python/workspace/server

    ports:
      - "${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}"


