version: "2.1"

services:

  python:
    image: approov/python-flask-shapes-demo
    build: ./docker
    restart: always
    env_file: .env
    environment:
      - FLASK_ENV=prod
    networks:
      - traefik
    command: "flask run -h 0.0.0.0 --port ${HTTP_PORT? Missing value for: HTTP_PORT}"
    volumes:
      - ./:/home/python/workspace
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${PYTHON_FLASK_SHAPES_DOMAIN? Missing value for: PYTHON_FLASK_SHAPES_DOMAIN}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT}"
      - "traefik.frontend.rule=Host:${PYTHON_FLASK_SHAPES_DOMAIN}"

networks:
  traefik:
    external: true
