version: "2.1"

services:

  dev:
    image: ${DOCKER_IMAGE:-approov/quickstart-python-flask-token-check:dev}
    build:
      context: ./docker
      args:
        BUILD_RELEASE_FROM: ${BUILD_RELEASE_FROM:-main} # pass through to container from .env file
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
    working_dir: "/home/python/workspace"
    command: "flask run -h 0.0.0.0 --port ${HTTP_PORT? Missing value for: HTTP_PORT}"
    volumes:
      - ./:/home/python/workspace
    ports:
      - 127.0.0.1:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    networks:
      - default

  python:
    image: ${DOCKER_IMAGE:-approov/quickstart-python-flask-token-check}
    build: ./docker
    restart: always
    env_file: .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-prod}
    networks:
      - traefik
    command: "flask run -h 0.0.0.0 --port ${HTTP_PORT? Missing value for: HTTP_PORT}"
    volumes:
      - ./:/home/python/workspace
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${SHAPES_PYTHON_FLASK_DOMAIN? Missing value for: SHAPES_PYTHON_FLASK_DOMAIN}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT}"
      - "traefik.frontend.rule=Host:${SHAPES_PYTHON_FLASK_DOMAIN}"

networks:
  traefik:
    external: true
